---
- name: Create Development EC2 Instance and Provision
  hosts: localhost
  vars:
    name: "{{ name }}"


  vars:
    name: "instance-1"
    instance_type: t2.micro
    ami: ami-e13739f6
# Set me
#    subnet_id: $subnet
#    key: $keyname

  tasks:
  - name: Launch instance
    ec2:
      key_name: "{{ key }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ subnet_id}}"
      assign_public_ip: yes
      region: "us-east-1"
      instance_tags:
        Name: "{{ name }}"
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    with_items: "{{ ec2.instances }}"

  - name: Add to inventory
    shell: echo "{{ name }}" ansible_user=ubuntu ansible_host="{{ item.public_ip }}" >> hosts
    with_items: "{{ ec2.instances }}"


  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"

  - name: Install goddamn python
    shell: ssh ubuntu@{{ item.public_ip }} -o StrictHostKeyChecking=no "sudo -u root bash -c 'apt-get -y install python'"
    with_items: "{{ ec2.instances }}"
